src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

   
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): static
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }
}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AppController!{% endblock %}

{% block body %}
<h1 class="text-center">Mon site de locations de voitures</h1> 
{% endblock %}

templates/app/showVehicule.html.twig
{% extends 'base.html.twig' %}


{% block title %}
    Show vehicule
{% endblock %}


{% block body %}
<div class="my-4">
    <div class="card text-white bg-dark my-5 text-center m-auto" style="max-width: 20rem;">
  <div class="card-header"> Titre : {{vehicule.titre}}</div>
  <div class="card-body">
    <h4 class="card-title">Marque : {{vehicule.marque}}</h4>
    <h4 class="card-title">Modele : {{vehicule.modele}}</h4>
    <h4 class="card-text"> Description : {{vehicule.description}}</h4>
  </div>  
 <a class="btn btn-success" href="{{ path('commandeAdd', {'id': vehicule.id}) }}">Passer commande</a>
  </div>
{% endblock %}

templates/app/voitures.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Voitures
{% endblock %}


{% block body %}
	<h1 class="text-center m-3">Liste des voitures</h1>
	<div class="container col-12">
		<table class="table table-dark m-5">
			<thead>
				<tr>
					<th>#</th>
					<th>Titre</th>
					<th>Marque</th>
					<th>Modele</th>
					<th>Description</th>
					<th>Photo</th>
					<th>Créer le</th>
					<th>Option</th>

				</tr>
			</thead>
			<tbody>
				{% for voiture in voitures %}
					<tr>
						<td>{{ voiture.id }}</td>
						<td>{{ voiture.titre }}</td>
						<td>{{ voiture.marque}}</td>
						<td>{{ voiture.modele}}</td>
						<td>{{ voiture.description}}</td>
						<td><img src="{{voiture.photo}}" alt="" width="50" height="50"></td>
						<td>{{ voiture.dateEnregistrement|date("d/m/Y à H:i:s") }}</td>
						<div>
							<td>
								<a href="{{ path('voitureShow', {id: voiture.id})}}">
									<i class="fa fa-eye"></i>
								</a>
							</td>
							{% if is_granted('ROLE_ADMIN') %}
								<td>
									<a href="{{ path('adminEdit', {id: voiture.id})}}">
										<i class="fa fa-edit"></i>
									</a>
								</td>
								<td>
									<a href="{{ path('adminEdit', {id: voiture.id})}}">
										<i class="fa fa-trash"></i>
									</a>
								</td>


							{% endif %}
						</div>

					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}